# Generated by Django 3.2.10 on 2022-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(blank=True, help_text="The package's version (eg. 0.8.0 or 1.2.3.4).", max_length=128),
        ),
    ]
