# Generated by Django 3.2.10 on 2022-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winget', '0002_alter_version_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='scope',
            field=models.CharField(choices=[('user', 'user'), ('machine', 'machine'), ('both', 'both')], default='both', help_text='Is this a machine-wide installer, just for the current user, or both?', max_length=7),
        ),
    ]
