# Generated by Django 3.2.10 on 2023-02-17 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winget', '0003_installer_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(help_text='Package description (e.g. "An open source differencing tool.")', max_length=256, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='identifier',
            field=models.CharField(help_text='Unique identifier for the package (e.g. WinMerge.WinMerge).', max_length=128),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(help_text='Package name (e.g. WinMerge).', max_length=256, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='publisher',
            field=models.CharField(help_text='Package publisher (eg. Thingamahoochie Software)', max_length=256, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(blank=True, help_text="The package's version (eg. 2.16.26 or 1.2.3.4).", max_length=128),
        ),
    ]
