# Generated by Django 3.2.10 on 2022-12-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winget', '0003_installer_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_version', models.CharField(blank=True, help_text='Eg. 0.8.0 or 1.2.3.4.', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winget.package')),
            ],
        ),
        migrations.AddField(
            model_name='installer',
            name='package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='winget.package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installer',
            name='version',
            field=models.CharField(blank=True, help_text="The package's version (eg. 0.8.0 or 1.2.3.4).", max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='installer',
            unique_together={('package', 'version', 'architecture', 'type')},
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.AddField(
            model_name='localdependency',
            name='installer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winget.installer'),
        ),
    ]
