# Generated by Django 3.2.20 on 2023-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winget', '0006_nested_installer'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='custom_switch',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='installer',
            name='install_location_switch',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='installer',
            name='interactive_switch',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='installer',
            name='log_switch',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='installer',
            name='silent_progress_switch',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='installer',
            name='silent_switch',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='installer',
            name='upgrade_switch',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
