# Generated by Django 3.2.20 on 2023-11-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winget', '0007_installer_switches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='custom_switch',
            field=models.CharField(blank=True, help_text='Custom command-line arguments to pass to the installer.', max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='install_location_switch',
            field=models.CharField(blank=True, help_text="The installer's command-line argument for a custom installation location. Use &lt;INSTALLPATH&gt; as placeholder.", max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='interactive_switch',
            field=models.CharField(blank=True, help_text="The installer's command-line argument for interactive installation.", max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='log_switch',
            field=models.CharField(blank=True, help_text="The installer's command-line argument for a custom log file path. Use &lt;LOGPATH&gt; as placeholder.", max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='silent_progress_switch',
            field=models.CharField(blank=True, help_text="The installer's command-line argument for non-interactive installation.", max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='silent_switch',
            field=models.CharField(blank=True, help_text="The installer's command-line argument for silent installation.", max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='upgrade_switch',
            field=models.CharField(blank=True, help_text="The installer's command-line argument when the user chooses an upgrade.", max_length=512),
        ),
    ]
