# Generated by Django 3.2.23 on 2024-02-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winget', '0008_add_installer_switches_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='custom_switch',
            field=models.CharField(blank=True, help_text="Setting this to abc always appends `abc` to the installer's command-line. Eg. `installer.exe abc`.", max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='install_location_switch',
            field=models.CharField(blank=True, help_text='Setting this to "abc &lt;INSTALLPATH&gt;" makes `winget install --location C:\\Dir` run `installer.exe abc C:\\Dir`.', max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='interactive_switch',
            field=models.CharField(blank=True, help_text='Setting this to abc makes `winget install --interactive` run `installer.exe abc`.', max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='log_switch',
            field=models.CharField(blank=True, help_text='Setting this to "abc &lt;LOGPATH&gt;" runs `installer.exe abc &lt;some file path&gt;`. Set the path with `winget install --log`.', max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='silent_progress_switch',
            field=models.CharField(blank=True, help_text='Setting this to abc makes `winget install` (without modifiers) run `installer.exe abc`.', max_length=512),
        ),
        migrations.AlterField(
            model_name='installer',
            name='silent_switch',
            field=models.CharField(blank=True, help_text='Setting this to abc makes `winget install --silent` run `installer.exe abc`.', max_length=512),
        ),
    ]
