# Generated by Django 3.2.10 on 2023-08-03 10:45

from django.db import migrations

def migrate_existing_users(apps, _):
    Tenant = apps.get_model('tenants', 'Tenant')
    for tenant in Tenant.objects.all():
        tenant.users.add(tenant.user)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_users'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_users)
    ]
